module.exports = {
  Aveiro: [
    { cod: 101, desc: "Águeda", district: 1 },
    { cod: 102, desc: "Albergaria-a-Velha", district: 1 },
    { cod: 103, desc: "Anadia", district: 1 },
    { cod: 104, desc: "Arouca", district: 1 },
    { cod: 105, desc: "Aveiro", district: 1 },
    { cod: 106, desc: "Castelo de Paiva", district: 1 },
    { cod: 107, desc: "Espinho", district: 1 },
    { cod: 108, desc: "Estarreja", district: 1 },
    { cod: 109, desc: "Ílhavo", district: 1 },
    { cod: 110, desc: "Mealhada", district: 1 },
    { cod: 111, desc: "Murtosa", district: 1 },
    { cod: 112, desc: "Oliveira de Azeméis", district: 1 },
    { cod: 113, desc: "Oliveira do Bairro", district: 1 },
    { cod: 114, desc: "Ovar", district: 1 },
    { cod: 115, desc: "Santa Maria da Feira", district: 1 },
    { cod: 116, desc: "São João da Madeira", district: 1 },
    { cod: 116, desc: "Sever do Vouga", district: 1 },
    { cod: 116, desc: "Vagos", district: 1 },
    { cod: 116, desc: "Vale de Cambra", district: 1 },
  ],
  Beja: [
    { cod: 201, desc: "Aljustrel", district: 2 },
    { cod: 202, desc: "Almodôvar", district: 2 },
    { cod: 203, desc: "Alvito", district: 2 },
    { cod: 204, desc: "Barrancos", district: 2 },
    { cod: 205, desc: "Beja", district: 2 },
    { cod: 206, desc: "Castro Verde", district: 2 },
    { cod: 207, desc: "Cuba", district: 2 },
    { cod: 208, desc: "Ferreira do Alentejo", district: 2 },
    { cod: 209, desc: "Mértola", district: 2 },
    { cod: 210, desc: "Moura", district: 2 },
    { cod: 211, desc: "Odemira", district: 2 },
    { cod: 212, desc: "Ourique", district: 2 },
    { cod: 213, desc: "Serpa", district: 2 },
    { cod: 214, desc: "Vidigueira", district: 2 },
  ],
  Braga: [
    { cod: 301, desc: "Amares", district: 3 },
    { cod: 302, desc: "Barcelos", district: 3 },
    { cod: 303, desc: "Braga", district: 3 },
    { cod: 304, desc: "Cabeceiras de Basto", district: 3 },
    { cod: 305, desc: "Celorico de Basto", district: 3 },
    { cod: 306, desc: "Esposende", district: 3 },
    { cod: 307, desc: "Fafe", district: 3 },
    { cod: 308, desc: "Guimarães", district: 3 },
    { cod: 309, desc: "Póvoa do Lanhoso", district: 3 },
    { cod: 310, desc: "Terras de Bouro", district: 3 },
    { cod: 311, desc: "Vieira do Minho", district: 3 },
    {
      cod: 312,
      desc: "Vila Nova de Famalicão",
      district: 3,
    },
    { cod: 313, desc: "Vila Verde", district: 3 },
    { cod: 314, desc: "Vizela", district: 3 },
  ],
  Bragança: [
    { cod: 401, desc: "Alfândega da Fé", district: 4 },
    { cod: 402, desc: "Bragança", district: 4 },
    { cod: 403, desc: "Carrazeda de Ansiães", district: 4 },
    {
      cod: 404,
      desc: "Freixo de Espada à Cinta",
      district: 4,
    },
    { cod: 405, desc: "Macedo de Cavaleiros", district: 4 },
    { cod: 406, desc: "Miranda do Douro", district: 4 },
    { cod: 407, desc: "Mirandela", district: 4 },
    { cod: 408, desc: "Mogadouro", district: 4 },
    { cod: 409, desc: "Torre de Moncorvo", district: 4 },
    { cod: 410, desc: "Vila de Flor", district: 4 },
    { cod: 411, desc: "Vimioso", district: 4 },
    { cod: 412, desc: "Vinhais", district: 4 },
  ],
  "Castelo Branco": [
    { cod: 501, desc: "Belmonte", district: 5 },
    { cod: 502, desc: "Castelo Branco", district: 5 },
    { cod: 503, desc: "Covilhã", district: 5 },
    { cod: 504, desc: "Fundão", district: 5 },
    { cod: 505, desc: "Idanha-a-Nova", district: 5 },
    { cod: 506, desc: "Oleiros", district: 5 },
    { cod: 507, desc: "Penamancor", district: 5 },
    { cod: 508, desc: "Proença-a-Nova", district: 5 },
    { cod: 509, desc: "Sertã", district: 5 },
    { cod: 510, desc: "Vila de Rei", district: 5 },
    { cod: 511, desc: "Vila Velha de Rodão", district: 5 },
  ],
  Coimbra: [
    { cod: 601, desc: "Arganil", district: 6 },
    { cod: 602, desc: "Cantanhede", district: 6 },
    { cod: 603, desc: "Coimbra", district: 6 },
    { cod: 604, desc: "Condeixa-a-Nova", district: 6 },
    { cod: 605, desc: "Figueira da Foz", district: 6 },
    { cod: 606, desc: "Góis", district: 6 },
    { cod: 607, desc: "Lousã", district: 6 },
    { cod: 608, desc: "Mira", district: 6 },
    { cod: 609, desc: "Miranda do Corvo", district: 6 },
    { cod: 610, desc: "Montemor-o-Velho", district: 6 },
    { cod: 611, desc: "Oliveira do Hospital", district: 6 },
    { cod: 612, desc: "Pampilhosa da Serra", district: 6 },
    { cod: 613, desc: "Penacova", district: 6 },
    { cod: 614, desc: "Penela", district: 6 },
    { cod: 614, desc: "Soure", district: 6 },
    { cod: 614, desc: "Tábua", district: 6 },
    { cod: 614, desc: "Vila Nova de Poiares", district: 6 },
  ],
  Évora: [
    { cod: 701, desc: "Alandroal", district: 7 },
    { cod: 702, desc: "Arraiolos", district: 7 },
    { cod: 703, desc: "Borba", district: 7 },
    { cod: 704, desc: "Estremoz", district: 7 },
    { cod: 705, desc: "Évora", district: 7 },
    { cod: 706, desc: "Montemor-o-Novo", district: 7 },
    { cod: 707, desc: "Mora", district: 7 },
    { cod: 708, desc: "Mourão", district: 7 },
    { cod: 709, desc: "Portel", district: 7 },
    { cod: 710, desc: "Redondo", district: 7 },
    {
      cod: 711,
      desc: "Reguengos de Monsaraz",
      district: 7,
    },
    { cod: 712, desc: "Vendas Novas", district: 7 },
    { cod: 713, desc: "Viana do Alentejo", district: 7 },
    { cod: 714, desc: "Vila Viçosa", district: 7 },
  ],
  Faro: [
    { cod: 801, desc: "Albufeira", district: 8 },
    { cod: 802, desc: "Alcoutim", district: 8 },
    { cod: 803, desc: "Aljezur", district: 8 },
    { cod: 804, desc: "Castro Marim", district: 8 },
    { cod: 805, desc: "Faro", district: 8 },
    { cod: 806, desc: "Lagoa", district: 8 },
    { cod: 807, desc: "Lagos", district: 8 },
    { cod: 808, desc: "Loulé", district: 8 },
    { cod: 809, desc: "Monchique", district: 8 },
    { cod: 810, desc: "Olhão", district: 8 },
    { cod: 811, desc: "Portimão", district: 8 },
    { cod: 812, desc: "São Brás de Alportel", district: 8 },
    { cod: 813, desc: "Silves", district: 8 },
    { cod: 814, desc: "Tavira", district: 8 },
    { cod: 814, desc: "Vila do Bispo", district: 8 },
    {
      cod: 814,
      desc: "Vila Real de Santo António",
      district: 8,
    },
  ],
  Guarda: [
    { cod: 901, desc: "Aguiar da Beira", district: 9 },
    { cod: 902, desc: "Almeida", district: 9 },
    { cod: 903, desc: "Celorico da Beira", district: 9 },
    {
      cod: 904,
      desc: "Figueira de Castelo Rodrigo",
      district: 9,
    },
    { cod: 905, desc: "Fornos de Algodres", district: 9 },
    { cod: 906, desc: "Gouveia", district: 9 },
    { cod: 907, desc: "Guarda", district: 9 },
    { cod: 908, desc: "Manteigas", district: 9 },
    { cod: 909, desc: "Mêda", district: 9 },
    { cod: 910, desc: "Pinhel", district: 9 },
    { cod: 911, desc: "Sabugal", district: 9 },
    { cod: 912, desc: "Seia", district: 9 },
    { cod: 913, desc: "Trancoso", district: 9 },
    { cod: 914, desc: "Vila Nova de Foz Côa", district: 9 },
  ],
  Leiria: [
    { cod: 1001, desc: "Alcobaça", district: 10 },
    { cod: 1002, desc: "Alvaiázere", district: 10 },
    { cod: 1003, desc: "Ansião", district: 10 },
    { cod: 1004, desc: "Batalha", district: 10 },
    { cod: 1005, desc: "Bombarral", district: 10 },
    { cod: 1006, desc: "Caldas da Rainha", district: 10 },
    {
      cod: 1007,
      desc: "Castanheira de Pêra",
      district: 10,
    },
    {
      cod: 1008,
      desc: "Figueiró dos Vinhos",
      district: 10,
    },
    { cod: 1009, desc: "Leiria", district: 10 },
    { cod: 1010, desc: "Marinha Grande", district: 10 },
    { cod: 1011, desc: "Nazaré", district: 10 },
    { cod: 1012, desc: "Óbidos", district: 10 },
    { cod: 1013, desc: "Pedrógão Grande", district: 10 },
    { cod: 1014, desc: "Peniche", district: 10 },
    { cod: 1015, desc: "Pombal", district: 10 },
    { cod: 1016, desc: "Porto de Mós", district: 10 },
  ],
  Lisboa: [
    { cod: 1101, desc: "Alenquer", district: 11 },
    { cod: 1102, desc: "Amadora", district: 11 },
    { cod: 1103, desc: "Arruda dos Vinhos", district: 11 },
    { cod: 1104, desc: "Azambuja", district: 11 },
    { cod: 1105, desc: "Cadaval", district: 11 },
    { cod: 1106, desc: "Cascais", district: 11 },
    { cod: 1107, desc: "Lisboa", district: 11 },
    { cod: 1108, desc: "Loures", district: 11 },
    { cod: 1109, desc: "Lourinhã", district: 11 },
    { cod: 1110, desc: "Mafra", district: 11 },
    { cod: 1111, desc: "Odivelas", district: 11 },
    { cod: 1112, desc: "Oeiras", district: 11 },
    { cod: 1113, desc: "Sintra", district: 11 },
    {
      cod: 1114,
      desc: "Sobral de Monte Agraço",
      district: 11,
    },
    { cod: 1114, desc: "Torres Vedras", district: 11 },
    {
      cod: 1114,
      desc: "Vila Franca de Xira",
      district: 11,
    },
  ],
  Portalegre: [
    { cod: 1201, desc: "Elvas", district: 12 },
    { cod: 1202, desc: "Portalegre", district: 12 },
    { cod: 1203, desc: "Ponte de Sôr", district: 12 },
    { cod: 1204, desc: "Campo Maior", district: 12 },
    { cod: 1205, desc: "Nisa", district: 12 },
    { cod: 1206, desc: "Alter do Chão", district: 12 },
    { cod: 1207, desc: "Castelo de Vide", district: 12 },
    { cod: 1208, desc: "Fronteira", district: 12 },
    { cod: 1209, desc: "Arronches", district: 12 },
    { cod: 1210, desc: "Sousel", district: 12 },
    { cod: 1211, desc: "Avis", district: 12 },
    { cod: 1212, desc: "Crato", district: 12 },
    { cod: 1213, desc: "Gavião", district: 12 },
    { cod: 1214, desc: "Monforte", district: 12 },
    { cod: 1215, desc: "Marvão", district: 12 },
  ],
  Porto: [
    { cod: 1301, desc: "Amarante", district: 13 },
    { cod: 1302, desc: "Baião", district: 13 },
    { cod: 1303, desc: "Felgueiras", district: 13 },
    { cod: 1304, desc: "Gondomar", district: 13 },
    { cod: 1305, desc: "Lousada", district: 13 },
    { cod: 1306, desc: "Maia", district: 13 },
    { cod: 1307, desc: "Marco de Canaveses", district: 13 },
    { cod: 1308, desc: "Matosinhos", district: 13 },
    { cod: 1309, desc: "Paços de Ferreira", district: 13 },
    { cod: 1310, desc: "Paredes", district: 13 },
    { cod: 1311, desc: "Penafiel", district: 13 },
    { cod: 1312, desc: "Porto", district: 13 },
    { cod: 1313, desc: "Póvoa do Varzim", district: 13 },
    { cod: 1314, desc: "Santo Tirso", district: 13 },
    { cod: 1315, desc: "Trofa", district: 13 },
    { cod: 1316, desc: "Valongo", district: 13 },
    { cod: 1317, desc: "Vila do Conde", district: 13 },
    { cod: 1318, desc: "Vila Nova de Gaia", district: 13 },
  ],
  Santarém: [
    { cod: 1401, desc: "Abrantes", district: 14 },
    { cod: 1402, desc: "Alcanena", district: 14 },
    { cod: 1403, desc: "Almeirim", district: 14 },
    { cod: 1404, desc: "Alpiarça", district: 14 },
    { cod: 1405, desc: "Benavente", district: 14 },
    { cod: 1406, desc: "Cartaxo", district: 14 },
    { cod: 1407, desc: "Chamusca", district: 14 },
    { cod: 1408, desc: "Constância", district: 14 },
    { cod: 1409, desc: "Coruche", district: 14 },
    { cod: 1410, desc: "Entroncamento", district: 14 },
    { cod: 1411, desc: "Ferreira do Zêzere", district: 14 },
    { cod: 1412, desc: "Golegã", district: 14 },
    { cod: 1413, desc: "Mação", district: 14 },
    { cod: 1414, desc: "Ourém", district: 14 },
    { cod: 1415, desc: "Rio Maior", district: 14 },
    {
      cod: 1416,
      desc: "Salvaterra de Magos",
      district: 14,
    },
    { cod: 1417, desc: "Santarém", district: 14 },
    { cod: 1418, desc: "Sardoal", district: 14 },
    { cod: 1419, desc: "Tomar", district: 14 },
    { cod: 1420, desc: "Torres Novas", district: 14 },
    {
      cod: 1421,
      desc: "Vila Nova da Barquinha",
      district: 14,
    },
  ],
  Setúbal: [
    { cod: 1501, desc: "Alcácer do Sal", district: 15 },
    { cod: 1502, desc: "Alcochete", district: 15 },
    { cod: 1503, desc: "Almada", district: 15 },
    { cod: 1504, desc: "Barreiro", district: 15 },
    { cod: 1505, desc: "Grândola", district: 15 },
    { cod: 1506, desc: "Moita", district: 15 },
    { cod: 1507, desc: "Montijo", district: 15 },
    { cod: 1508, desc: "Palmela", district: 15 },
    { cod: 1509, desc: "Santiago do Cacém", district: 15 },
    { cod: 1510, desc: "Seixal", district: 15 },
    { cod: 1511, desc: "Sesimbra", district: 15 },
    { cod: 1512, desc: "Setúbal", district: 15 },
    { cod: 1513, desc: "Sines", district: 15 },
  ],
  "Viana do Castelo": [
    { cod: 1601, desc: "Arcos de Valdevez", district: 16 },
    { cod: 1602, desc: "Caminha", district: 16 },
    { cod: 1603, desc: "Melgaço", district: 16 },
    { cod: 1604, desc: "Monção", district: 16 },
    { cod: 1605, desc: "Paredes de Coura", district: 16 },
    { cod: 1606, desc: "Ponte de Barca", district: 16 },
    { cod: 1607, desc: "Ponte de Lima", district: 16 },
    { cod: 1608, desc: "Valença", district: 16 },
    { cod: 1609, desc: "Viana do Castelo", district: 16 },
    {
      cod: 1610,
      desc: "Vila Nova de Cerveira",
      district: 16,
    },
  ],
  "Vila Real": [
    { cod: 1701, desc: "Alijó", district: 17 },
    { cod: 1702, desc: "Boticas", district: 17 },
    { cod: 1703, desc: "Chaves", district: 17 },
    { cod: 1704, desc: "Mesão Frio", district: 17 },
    { cod: 1705, desc: "Mondim de Basto", district: 17 },
    { cod: 1706, desc: "Montalegre", district: 17 },
    { cod: 1707, desc: "Murça", district: 17 },
    { cod: 1708, desc: "Peso da Régua", district: 17 },
    { cod: 1709, desc: "Ribeira de Pena", district: 17 },
    { cod: 1710, desc: "Sabrosa", district: 17 },
    {
      cod: 1711,
      desc: "Santa Marta de Penaguião",
      district: 17,
    },
    { cod: 1712, desc: "Valpaços", district: 17 },
    {
      cod: 1713,
      desc: "Vila Pouca de Aguiar",
      district: 17,
    },
    { cod: 1714, desc: "Vila Real", district: 17 },
  ],
  Viseu: [
    { cod: 1801, desc: "Armamar", district: 18 },
    { cod: 1802, desc: "Carregal do Sal", district: 18 },
    { cod: 1803, desc: "Castro Daire", district: 18 },
    { cod: 1804, desc: "Cinfães", district: 18 },
    { cod: 1805, desc: "Lamego", district: 18 },
    { cod: 1806, desc: "Mangualde", district: 18 },
    { cod: 1807, desc: "Moimenta da Beira", district: 18 },
    { cod: 1808, desc: "Mortágua", district: 18 },
    { cod: 1809, desc: "Nelas", district: 18 },
    { cod: 1810, desc: "Oliveira de Frades", district: 18 },
    { cod: 1811, desc: "Penalva do Castelo", district: 18 },
    { cod: 1812, desc: "Penedono", district: 18 },
    { cod: 1813, desc: "Resende", district: 18 },
    { cod: 1814, desc: "Santa Comba Dão", district: 18 },
    {
      cod: 1815,
      desc: "São João da Pesqueira",
      district: 18,
    },
    { cod: 1816, desc: "São Pedro do Sul", district: 18 },
    { cod: 1817, desc: "Sátão", district: 18 },
    { cod: 1818, desc: "Sernancelhe", district: 18 },
    { cod: 1819, desc: "Tabuaço", district: 18 },
    { cod: 1820, desc: "Tarouca", district: 18 },
    { cod: 1821, desc: "Tondela", district: 18 },
    { cod: 1822, desc: "Vila Nova de Paiva", district: 18 },
    { cod: 1823, desc: "Viseu", district: 18 },
    { cod: 1824, desc: "Vouzela", district: 18 },
  ],
};
