module.exports = [
  { cod: 1, abrev: "AVR", desc: "Aveiro" },
  { cod: 2, abrev: "BEJ", desc: "Beja" },
  { cod: 3, abrev: "BRA", desc: "Braga" },
  { cod: 4, abrev: "BRG", desc: "Bragança" },
  { cod: 5, abrev: "CAB", desc: "Castelo Branco" },
  { cod: 6, abrev: "CBR", desc: "Coimbra" },
  { cod: 7, abrev: "EVR", desc: "Évora" },
  { cod: 8, abrev: "FAR", desc: "Faro" },
  { cod: 9, abrev: "GUA", desc: "Guarda" },
  { cod: 10, abrev: "LRA", desc: "Leiria" },
  { cod: 11, abrev: "LSB", desc: "Lisboa" },
  { cod: 12, abrev: "PTG", desc: "Portalegre" },
  { cod: 13, abrev: "POR", desc: "Porto" },
  { cod: 14, abrev: "STR", desc: "Santarém" },
  { cod: 15, abrev: "SET", desc: "Setubal" },
  { cod: 16, abrev: "VCT", desc: "Viana do Castelo" },
  { cod: 17, abrev: "VRL", desc: "Vila Real" },
  { cod: 18, abrev: "VIS", desc: "Viseu" },
  { cod: 31, abrev: "MAD", desc: "Ilha da Madeira" },
  { cod: 32, abrev: "PST", desc: "Ilha de Porto Santo" },
  { cod: 41, abrev: "SMA", desc: "Ilha Santa Maria" },
  { cod: 42, abrev: "SMI", desc: "Ilha São Miguel" },
  { cod: 43, abrev: "TER", desc: "Ilha Terceira" },
  { cod: 44, abrev: "GRA", desc: "Ilha da Graciosa" },
  { cod: 45, abrev: "SJG", desc: "Ilha São Jorge" },
  { cod: 46, abrev: "PIC", desc: "Ilha do Pico" },
  { cod: 47, abrev: "FAI", desc: "Ilha do Faial" },
  { cod: 48, abrev: "FLO", desc: "Ilha das Flores" },
  { cod: 49, abrev: "COR", desc: "Ilha do Corvo" },
];
